// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdulaqjmhawqodouddca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdWxhcWptaGF3cW9kb3VkZGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODc3MjUsImV4cCI6MjA2NzU2MzcyNX0.37zC1IpNCh7FT_lnrXhABqUiJp9lZHIjxMT2ByED-WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});